---
- name: "Install dependencies"
  become: true
  apt:
    name: ["python3", "nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present