---
- name: "Install dependencies"
  become: true
  apt:
    name: ["python3", "nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes