---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src:  files/artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  environment:
      # Get the environment variables from CircleCI and add to the EC2 instance
      ENVIRONMENT: production
      NODE_ENV: production
      VERSION: "1"
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js" 
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
  shell: |
    cd ~/backend-app
    npm i
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"


- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
